version: "3"
services:
  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE}

  client:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - server
