version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    image: ${REPOSITORY_NAME}/server

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - server
    environment:
      - API_URL=${API_URL}
    image: ${REPOSITORY_NAME}/server
