services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER} 
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - mongo_network

  mongo_client:
    image: mongo:latest
    container_name: mongo_client
    command: ["mongo", "-u", "${DATABASE_USER}", "-p", "${DATABASE_PASSWORD}", "--authenticationDatabase", "${DATABASE_NAME}", "mongodb://mongodb:27017"]
    depends_on:
      - mongodb
    networks:
      - mongo_network

volumes:
  mongo_data:
    driver: local

networks:
  mongo_network:
    driver: bridge
